### ISSUE TITLE
 java.lang.UnsupportedClassVersionError: io/logz/jmx2graphite/Jmx2GraphiteJavaAgent : Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by atulatri** [logzio/jmx2graphite#11]
Hi,

I tried running jmx2graphite-1.1.0-javaagent.jar with java 7 in agent mode. I get error "Unsupported major.minor version 52.0".

Will it compile with java 7? Do you have any guide instructing how to build from source?

Thanks & Regards,
Atul Atri.

**Comment by atulatri** [comment]
Just checked build.gradle.  
sourceCompatibility  is 1.8. :(

**Comment by asafm** [comment]
Isn't 7 at end of life?

**Comment by atulatri** [comment]
@asafm
Thanks for prompt response.

Yes it is.

But our company is still using java 7. :|

**Comment by asafm** [comment]
Feel free to fork and adjust to 7. It's not that much work I think
