### ISSUE TITLE
unable to create class Log4JContextFactory after adding jmx2graphite-1.2.1-javaagent.jar in JAVA_OPTS

### ISSUE THREAD

**Issue by Birajpjpt** [logzio/jmx2graphite#15]
I'm getting this error `ERROR StatusLogger Unable to create class org.apache.logging.log4j.core.impl.Log4jContextFactory specified in jar:file:/opt/jmx2graphite-1.2.1-javaagent.jar!/META-INF/log4j-provider.properties` when I added the javaagent jar to my JAVA_OPTS.

**Comment by nasis** [comment]
Thanks. Fixed. Please take a look at v1.2.2
