### ISSUE TITLE
Missing stats and how to list exported metrics

### ISSUE THREAD

**Issue by wawrzek** [logzio/jmx2graphite#2]
I don't see a way to list metrics send to graphite. We notice some mbeans in Jolokia, but not in grahpite and I try to understand why they were missed.

**Comment by asafm** [comment]
One of way to tracing those mbeans is adding this XML section to logback.xml found in the conf directory:

```
    <logger name="io.logz.jmx2graphite.MetricsPoller" level="TRACE"/>
```

ssh into the running container by issuing:

```
docker exec -it jmx2graphite bash
```

Edit /opt/jmx2graphite/conf/logback.xml and add the section above there. After 30 seconds of saving the file you will start seeing those trace messages. You can turn it off by commenting this XML section out and saving the file.

Tell me if that accomplishes your goal - if not let's try to work out a solution.

Oh - one important detail: Graphite only stores numeric values, so jmx2graphite filters out any MBean attribute which has a non numeric value (like a string). I can actually debug this as well as "how many non metrics were dropped" by that's a bit more work. Let's start with the existing solution and see how it works.

**Comment by wawrzek** [comment]
In regards of attribute type. Is "java.lang.Long" a potential problem?

In regards on debugging. I don't see any change in logs after adding suggested section. I tried:
 `<logger name="io.logz.jmx2graphite" level="TRACE"/>`
and see some extra output, but on DEBUG not TRACE level. And not a log of it.

```
16/03/14 16:48:17 DEBUG i.l.j.JolokiaClient: Retrieving /list of bean from Jolokia (http://10.0.1.4:31338/monitoring/json/)...
16/03/14 16:48:17 DEBUG i.l.j.JolokiaClient: GET /list from jolokia took 265 ms
16/03/14 16:48:17 INFO i.l.j.MetricsPoller: Found 288 metric beans. Time = 271ms, for Mon Mar 14 16:48:00 UTC 2016
16/03/14 16:48:17 INFO i.l.j.MetricsPoller: metrics fetched. Time: 206 ms; Metrics: 5362
16/03/14 16:48:17 DEBUG i.l.j.PickledGraphite: Wrote 400 metrics
16/03/14 16:48:17 DEBUG i.l.j.PickledGraphite: Wrote 400 metrics
16/03/14 16:48:17 DEBUG i.l.j.PickledGraphite: Wrote 400 metrics
16/03/14 16:48:17 DEBUG i.l.j.PickledGraphite: Wrote 400 metrics
16/03/14 16:48:17 DEBUG i.l.j.PickledGraphite: Wrote 400 metrics
16/03/14 16:48:17 DEBUG i.l.j.PickledGraphite: Wrote 400 metrics
16/03/14 16:48:17 DEBUG i.l.j.PickledGraphite: Wrote 400 metrics
16/03/14 16:48:17 DEBUG i.l.j.PickledGraphite: Wrote 400 metrics
16/03/14 16:48:17 DEBUG i.l.j.PickledGraphite: Wrote 400 metrics
16/03/14 16:48:17 DEBUG i.l.j.PickledGraphite: Wrote 400 metrics
16/03/14 16:48:17 DEBUG i.l.j.PickledGraphite: Wrote 400 metrics
16/03/14 16:48:17 DEBUG i.l.j.PickledGraphite: Wrote 400 metrics
16/03/14 16:48:17 DEBUG i.l.j.PickledGraphite: Wrote 400 metrics
16/03/14 16:48:17 DEBUG i.l.j.PickledGraphite: Wrote 162 metrics
16/03/14 16:48:17 INFO i.l.j.MetricsPoller: metrics sent to Graphite. Time: 65 ms, Failed metrics: 0
```

**Comment by asafm** [comment]
Sorry, I've noticed the limit on the log file appender is to DEBUG. Change it to:

```
        <filter class="ch.qos.logback.classic.filter.ThresholdFilter">
            <level>TRACE</level>
        </filter>
```

I will fix this now on master

**Comment by asafm** [comment]
Regarding Long vs long: Any null value will make this attribute filter out and not sent to Graphite, thus in Graphite you will a null value (missing) for this timestamp.

**Comment by asafm** [comment]
@wawrzek Can I close this?

**Comment by wawrzek** [comment]
Please do.
