### ISSUE TITLE
Memory leaks

### ISSUE THREAD

**Issue by pikrzysztof** [logzio/jmx2graphite#22]
jmx2graphite seems to be leaking memory.

This is the graph of the memory usage:

![screenshot from 2018-09-06 19-17-02](https://user-images.githubusercontent.com/3964215/45176978-8758e580-b209-11e8-93ee-885d6c128d42.png)

I was running a previous version of this and it didn't leak any memory. 

Can you please help me?

**Comment by asafm** [comment]
Sure we can help @pikrzysztof.
Why do think it's leaking? Peak memory doesn't seem to be in an increasing rate.
Which version are you running now, and which is previous?

**Comment by pikrzysztof** [comment]
Sorry, I haven't described the graph. I run it in kubernetes which kills it as soon as it reaches 512Mi. I have increased the limit to 2Gi and I see that it needs about 630Mi to work and doesn't leak.
