### ISSUE TITLE
Picking only first parameter when running jmx2graphite as java agent

### ISSUE THREAD

**Issue by er-rishi** [logzio/jmx2graphite#26]
When running the below command: 
`java -javaagent:./jmx2graphite-1.2.4-javaagent.jar=GRAPHITE_HOSTNAME=localhost;SERVICE_NAME=MyApp example.jar`

getting below error:
```
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
	at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
Caused by: io.logz.jmx2graphite.IllegalConfiguration: SERVICE_NAME must be one of the arguments
	at io.logz.jmx2graphite.Jmx2GraphiteJavaAgent.premain(Jmx2GraphiteJavaAgent.java:30)
	... 6 more
FATAL ERROR in native method: processing of -javaagent failed

```

It looks like that it is picking only first parameter, not all. Please let me know if I am doing something wrong or this is really a bug ?

**Comment by er-rishi** [comment]
Can anyone please guide me for the above? I don't want to run a separate docker instance for jmx2graphite, I want to run it as a part of the service docker instance only.

**Comment by guillaumelfv** [comment]
I have the exact same issue.

> java -version
> openjdk version "1.8.0_191"
> OpenJDK Runtime Environment (build 1.8.0_191-b12)
> OpenJDK 64-Bit Server VM (build 25.191-b12, mixed mode)

**Comment by er-rishi** [comment]
Need help on urgent basis. Please let me know how can I make it run as java agent.

**Comment by yyyogev** [comment]
This is a known problem that we currently fixing, we will soon release an update for it.
Thanks for pointing that out

**Comment by er-rishi** [comment]
Thanks @yyyogev for the update. Waiting for that release.

**Comment by er-rishi** [comment]
Hi @yyyogev , When can I expect the release for jmx2graphite as java agent? 

I need to monitor multiple applications but I can not run one jmx2graphite for each application. I need a solution where I want to run a single jmx2graphite for multiple applications. is it possible currently?

**Comment by yyyogev** [comment]
@er-rishi  very soon, probably Sunday or Monday

**Comment by er-rishi** [comment]
Great. That would be really awesome. thanks

**Comment by yyyogev** [comment]
@er-rishi, @guillaumelfv jmx2graphite now supports comma as an argument delimiter in addition to semicolon

**Comment by er-rishi** [comment]
Thanks @yyyogev . Also I did not see the agent jar for 1.2.5. Can you please update the release with the 1.2.5. Thanks

**Comment by yyyogev** [comment]
@er-rishi we added a new release. Let me know if everything works out

**Comment by er-rishi** [comment]
yeah, I just noticed. Earlier it was not there then I my self built the javaagent and tried that. It is working fine now. Thanks for making the fix. @yyyogev

**Comment by er-rishi** [comment]
Hi @yyyogev For the uniformity, can you please add javaagent as a suffix to the new version i.e. 1.2.5 ?

**Comment by yyyogev** [comment]
Done
Thanks @er-rishi for mentioning

**Comment by er-rishi** [comment]
No Problem @yyyogev
