### ISSUE TITLE
Configurable LOG LEVEL

### ISSUE THREAD

**Issue by DanielFidalgo** [logzio/jmx2graphite#55]
Currently MetricsPipeline.java spits out too much logging that goes on top of application log.
Adding a way to configure log level at agent invocation should solve this

**Comment by DanielFidalgo** [comment]
It got merged =). Is it possible to get a v1.3.2 release of the java agent so I can wget it into a docker file? Thanks

**Comment by yyyogev** [comment]
Of course! I issued a new release now
