### ISSUE TITLE
JMX2Graphite not exposing connector and task status metrics

### ISSUE THREAD

**Issue by Yatharth0045** [logzio/jmx2graphite#62]
Deployed Kafka Connect with JMX2Graphite but not able to get all the metrics. As per the [Kafka Documentation](https://kafka.apache.org/documentation/#connect_monitoring), we should be getting **kafka.connect:type=connector-metrics** & **status** for **kafka.connect:type=connector-task-metrics,connector** 

> Steps to reproduce

Added jmx2graphite jar in kafka-connect docker image and pass the required jar environments as `KAFKA_OPTS` env to kafka-connect docker image as:

```bash
KAFKA_OPTS="-javaagent:jmx2graphite-1.4.1-javaagent.jar=GRAPHITE_HOSTNAME=localhost,GRAPHITE_PORT=80,SERVICE_HOST=svc-host,SERVICE_NAME=kafka"
```

Here, I'm able to get all the kafka connect specified metrics except:

type | attributes
------------ | -------------
connector-metrics | all
connector-task-metrics | status

Please help me to enable these metrics.

**Comment by yyyogev** [comment]
@Yatharth0045 Jmx2graphite filters metrics only if you set the BLACK_LIST_REGEX or WHITE_LIST_REGEX parameters.
Try to run the agent in debug mode and see if you get any "Failed" messages.
Could you please share the Dockerfile you used to build the image?

**Comment by Yatharth0045** [comment]
@yyyogev , Here's the Docker file. I have downloaded the jar on my local and build this Dockerfile

```bash
FROM confluentinc/cp-kafka-connect:4.0.0
COPY jmx2graphite-1.4.1-javaagent.jar /
```

Also, I haven't provided any **WHITE_LIST_REGEX** and **BLACK_LIST_REGEX**

**Comment by yyyogev** [comment]
@Yatharth0045 did you try to run the agent in debug mode and see if you get any "Failed" messages?

**Comment by Yatharth0045** [comment]
Yes @yyyogev 
I even tried with LOG_LEVEL as debug and got the following logs
```bash
19/12/16 07:31:23 INFO jmx2graphite.MetricsPipeline: Found 117 metric beans. Time = 8ms, for 2019-12-16T07:31:00.000+0000
19/12/16 07:31:23 INFO jmx2graphite.MetricsPipeline: metrics fetched. Time: 32 ms; Metrics: 1048
19/12/16 07:31:23 DEBUG jmx2graphite.PickledGraphite: Wrote 400 metrics
19/12/16 07:31:23 DEBUG jmx2graphite.PickledGraphite: Wrote 400 metrics
19/12/16 07:31:23 DEBUG jmx2graphite.PickledGraphite: Wrote 248 metrics
19/12/16 07:31:23 INFO jmx2graphite.MetricsPipeline: metrics sent to Graphite. Time: 9 ms, Failed metrics: 0
```

By the way, @yyyogev I'm not getting only the specified metrics of kafka.

Also, regarding the **Blacklisting metrics** property, I've tried the jmx2graphite 3.2.0 version also, but still didn't able to get those metrics.

**Comment by Yatharth0045** [comment]
Also, According to jmx2graphite [README](https://github.com/logzio/jmx2graphite/blob/master/README.md), I've updated the **MAX_CREATES_PER_MINUTE** and **MAX_UPDATES_PER_SECOND** configuration to 10000 instead of default.

**Comment by mayank-bairagi** [comment]
@yyyogev  , I am facing the same issue as @Yatharth0045. On stackoverflow, I found a similar [thread](https://stackoverflow.com/questions/50291157/which-jmx-metric-should-be-used-to-monitor-the-status-of-a-connector-in-kafka-co/50291687). Can anyone provide pointers to address the issue?

**Comment by yyyogev** [comment]
Could you share the steps to reproduce? Dockerfile?

**Comment by yyyogev** [comment]
Do any of you guys using logz.io? 
We have a much more stable tool to extract jmx metrics to logz.io - [Jmx2Logzio](https://github.com/logzio/jmx2logzio)
Try and see if you can get those metrics with this tool, then we'll know for sure that there is something wrong.

**Comment by asafm** [comment]
@mbairagi85 Please re-run it , this time with TRACE log level. It should print out the metrics it fetched. It's a little more hint in the direction.

**Comment by Yatharth0045** [comment]
Thanks @asafm. This was helpful for debugging. And yes, jmx2graphite is not able to fetch the required metrics.

**Comment by Yatharth0045** [comment]
> @yyyogev , I am facing the same issue as @Yatharth0045. On stackoverflow, I found a similar [thread](https://stackoverflow.com/questions/50291157/which-jmx-metric-should-be-used-to-monitor-the-status-of-a-connector-in-kafka-co/50291687). Can anyone provide pointers to address the issue?

I've already shared the **Dockerfile** above in the thread in which I've just added the jmx2graphite.jar in the kafka connect docker.

**Comment by Yatharth0045** [comment]
> Could you share the steps to reproduce? Dockerfile?

@yyyogev I've already shared the Dockerfile above in the thread in which I've just added the jmx2graphite.jar in the kafka connect docker and passed its config as **KAFKA_OPTS** variable as follows
```
KAFKA_OPTS="-javaagent:jmx2graphite.jar=GRAPHITE_HOSTNAME=172.17.0.6,GRAPHITE_PORT=2004,SERVICE_HOST=service,SERVICE_NAME=kafka-connect,LOG_LEVEL=DEBUG"
```

**Comment by yyyogev** [comment]
> And yes, jmx2graphite is not able to fetch the required metrics.

@Yatharth0045 What do you mean? Do you see those metrics with a failed message or can't see them at all?

**Comment by Yatharth0045** [comment]
Yes @yyyogev, I can't see them at all. 
Have you tried to reproduce the issue? Were you able to fetch those metrics?

**Comment by yyyogev** [comment]
I have but I couldn't manage to raise the whole kafka-zookeeper-graphite architecture.
Anyway, if you don't see the metrics at all with TRACE mode, it's not being exposed. This means that for your configuration, these metrics are unavailable/irrelevant.
Have you tried to observe these metrics with an external tool? Such as Jconsole, [Hawtio](https://hawt.io/)?

**Comment by Yatharth0045** [comment]
Yes @yyyogev, I'm able to get those metrics via **Jconsole**. Also, I have observed that all the metrics which I'm not able to fetch has some string value and not a numeric value. Maybe that's why JMX2Graphite wasn't able to pick and store them in graphite.

**Comment by yyyogev** [comment]
That has to be it. Our metric base unit is "name to a number" although it's super weird that you don't get any failed messages..
I'll try and release a fix for that in a few days

**Comment by yyyogev** [comment]
According to [Graphite docs](https://graphite.readthedocs.io/en/latest/overview.html#what-graphite-is-and-is-not), it can't store string metrics - "Store numeric time-series data".
Therefore, we won't issue the above fix.
