### ISSUE TITLE
Documentation error for docker deployment with config file

### ISSUE THREAD

**Issue by relyafi** [logzio/jmx2graphite#75]
The README.md file states the following command should be run to bring up a docker container with a configuration file:

`docker run -d -name jmx2graphtite -v path/to/config/myConfig.conf:application.conf logizo/jmx2graphite`

This seems to have several typos:

- the name argument should be --name, not -name
- typo in "jmx2graphtite" - doesn't cause issues, but confusing
- typo in image - should be "logzio" not "logizo"

**Comment by yyyogev** [comment]
Thanks @relyafi 
Fixed at https://github.com/logzio/jmx2graphite/pull/76
